FROM python:3.6.8-alpine

ARG APK_MIRROR
ARG PIP_MIRROR

RUN set -xe;\
   [ ! -z "${APK_MIRROR}" ]\
 && sed -e "s/dl-cdn\.alpinelinux\.org/${APK_MIRROR}/g" \
      -Ee 's!^http://!https://!g' \
      -i /etc/apk/repositories;\
    [ ! -z "${PIP_MIRROR}" ] && pip config set global.index-url ${PIP_MIRROR};\
    apk add --update --no-cache libvirt-libs openssh-client libxml2 libxslt\
      libxml2-dev libxslt-dev libvirt-dev gcc musl musl-dev\
 && pip install libvirt-python lxml\
 && apk del libxml2-dev libxslt-dev libvirt-dev gcc musl-dev

RUN set -xe\
 && mkdir -p /root/.ssh\
 && chmod 500 /root/.ssh\
 && echo 'Host *' > /root/.ssh/config\
 && echo ' StrictHostKeyChecking no' >> /root/.ssh/config\
 && echo ' IdentityFile /ssh_keys/id_rsa' >> /root/.ssh/config\
 && echo ' IdentityFile /ssh_keys/id_dsa' >> /root/.ssh/config\
 && echo ' IdentityFile /ssh_keys/id_ecdsa' >> /root/.ssh/config\
 && echo ' IdentityFile /ssh_keys/id_ed25519' >> /root/.ssh/config

VOLUME [ "/ssh_keys" ]